version: '3.8'

services:
  hebi-api:
    image: ${CI_REGISTRY_IMAGE}:${SHORT_SHA}
    ports:
      - "8080:8080"  # Matches your exposed ports
      - "8081:8081"
    networks:
      - hebi-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=hebiDb;User Id=postgres;Passwo¿rd=postgres;
      - RUN_MIGRATIONS=true  # Set to false after first run if needed
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    container_name: 'postgres'
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hebiDb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Hebi-Api/Migrations:/app/Migrations  # Only needed for development
    ports:
      - "5432:5432"
    networks:
      - hebi-api
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    
    
networks:
  hebi-api:
    external: true